import "./globals.css";
import { Manrope, Inter } from "next/font/google";
import Sidebar from "./components/Sidebar";

const manrope = Manrope({
  weights: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-manrope",
});

const inter = Inter({
  weights: ["400"],
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${manrope.variable} ${inter.variable}`}>
      <body className="flex flex-col md:flex-row md:px-80 h-dvh">
        <div className="md:w-[500px] py-10 px-5 md:py-20 md:px-10">
          <Sidebar />
        </div>
        <main className="py-10 px-5 md:flex-1 md:py-20 md:px-10 md:ml-10 md:overflow-y-auto">
          {children}
        </main>
      </body>
    </html>
  );
}
