import "./globals.css";
import { Manrope, Inter } from "next/font/google";
import Sidebar from "./components/Sidebar";

const manrope = Manrope({
  weights: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-manrope",
});

const inter = Inter({
  weights: ["400"],
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${manrope.variable} ${inter.variable}`}>
      <body className="">
        <div className="sidebar">
          <Sidebar />
        </div>
        <main className="content">{children}</main>
      </body>
    </html>
  );
}
